name: CI/CD with Render and DB (Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build Docker Image
      run: |
        docker build -t cicd-practice:latest .
    - name: Generate config.json from environment variables
      env:
        REDIS_URL: ${{ secrets.REDIS_URL }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DIALECT: ${{ secrets.DB_DIALECT }}
      run: |
        docker run --rm \
          -e REDIS_URL=$REDIS_URL \
          -e DB_HOST=$DB_HOST \
          -e DB_USER=$DB_USER \
          -e DB_PASSWORD=$DB_PASSWORD \
          -e DB_NAME=$DB_NAME \
          -e DB_PORT=$DB_PORT \
          -e DB_DIALECT=$DB_DIALECT \
          cicd-practice:latest node src/config/config.js  # Chạy script tạo config.json
    - name: Run Tests Inside Docker
      run: |
        docker run --rm cicd-practice:latest npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      run: |
        docker build -t cicd-practice:latest .
    - name: Generate config.json from environment variables
      env:
        REDIS_URL: ${{ secrets.REDIS_URL }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DIALECT: ${{ secrets.DB_DIALECT }}
      run: |
        docker run --rm \
          -e REDIS_URL=$REDIS_URL \
          -e DB_HOST=$DB_HOST \
          -e DB_USER=$DB_USER \
          -e DB_PASSWORD=$DB_PASSWORD \
          -e DB_NAME=$DB_NAME \
          -e DB_PORT=$DB_PORT \
          -e DB_DIALECT=$DB_DIALECT \
          cicd-practice:latest node src/config/config.js  # Chạy script tạo config.json
    - name: Run Migrations and Seeders
      env:
        REDIS_URL: ${{ secrets.REDIS_URL }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_PORT: ${{ secrets.DB_DIALECT }}
      run: |
        docker run --rm \
          -e REDIS_URL=$REDIS_URL \
          -e DB_HOST=$DB_HOST \
          -e DB_USER=$DB_USER \
          -e DB_PASSWORD=$DB_PASSWORD \
          -e DB_NAME=$DB_NAME \
          -e DB_PORT=$DB_PORT \
          -e DB_DIALECT=$DB_DIALECT \
          cicd-practice:latest npm run migrate && npm run seed
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"clearCache":true}' \
          https://api.render.com/v1/services/<RENDER_SERVICE_ID>/deploys
